### ISSUE TITLE
Research on sEMG signal

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#13]
[Folder](https://github.com/dymnz/sEMG/tree/master/Reports/%E7%8E%8B/Paper) | [Template](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/Template.MD)

* Important: ⭐
* Reading 🔥

### Papers
- [x]  [Surface electromyography applications in the sport](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/Surface%20electromyography%20applications%20in%20the%20sport.MD)
  - [x] [Effects of rate of force development on EMG amplitude and frequency](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/Effects%20of%20rate%20of%20force%20development%20on%20EMG%20amplitude%20and%20frequency.MD)
- [ ]  🔥 [The Application of sEMG in Aging: A Mini Review](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/The%20Application%20of%20sEMG%20in%20Aging%20-%20A%20Mini%20Review.MD)
  - [x] [Spectral properties of the surface EMG can characterize/do not provide
information about motor unit recruitment strategies and muscle fiber type](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/Spectral%20properties%20of%20the%20surface%20EMG%20can%20characterize:do%20not%20provide%20information%20about%20motor%20unit%20recruitment%20strategies%20and%20muscle%20fiber%20type.MD)
  - [ ] ⭐[The extraction of neural strategies from the surface EMG: an update](https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/The%20extraction%20of%20neural%20strategies%20from%20the%20surface%20EMG-%20an%20update.MD)
- [x]  Surface Electromyography Signal Processing and Application: A Review

### Meeting
* [Meeting 1](https://drive.google.com/open?id=12xDsDrCrDpMVEYe7B2tqdQ3GwobEBt-VJcQ6Def_-YM)

**Comment by dymnz** [comment]
https://github.com/dymnz/sEMG/blob/master/Reports/%E7%8E%8B/Paper/Effects%20of%20rate%20of%20force%20development%20on%20EMG%20amplitude%20and%20frequency.MD
