### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#35]
- [x] RNN test
  * [Note](https://github.com/dymnz/sEMG/blob/master/RNN/RNN_sim.md)
  - [x] Vanilla
    - [x] Convolution test
  - [x] LSTM
    - [x] Sensor fusion test
    - [x] Cross-validation w/ patience 
- [ ] 4-channel power supply PCB
  - [x] Design
  - [ ] Missed P+9V power line connection, to be fixed
    * Temp fixed, but still significant voltage drop w/ load. Use PSU instead.
  - [x] Test
    - [ ] Voltage drop >10% w/ load, need more test. Use PSU now
- [x] Additional circuit PCB
  - [x] Design
  - [x] Test
- [x] Angle measurement: 
  - [x] Acce.
  - [x] Pot. (Unusable, see #43)
  - [x] Magn. (#45) 
- [x] Grip force measurement: 
  * [Note](https://github.com/dymnz/sEMG/blob/master/Force/Loadcell/TAL220_straight_bar_10kg.md)
  - [x] Solder + test
  - [x] Woodwork
  - [x] Calibration
    - Calibration factor : -200000
    - Accuracy: to  be calculated

**Comment by dymnz** [comment]
Loadcell: No voltage change between O+ and O-, probably broken.

**Comment by dymnz** [comment]
- [x] Arduino Force-sEMG ADC
  - [x] sEMG read
      - [x] Find the best ADC circuit configuration to avoid clipping
        * Re-adjust for every session
  - [x] Force read
  - [x] Angle read
  - [x] Integration

- [x] RNN sEMG-Force estimation
  - [ ] Find best pre-process procedure  
    - [ ] PCA or ICA


- [ ] LSTM/ANN force estimation performance comparison
    * Method:
        - [ ] ANN implementation?  
        - [ ] LSTM modification?

**Comment by dymnz** [comment]
- [x] RNN sEMG-Angle estimation
  - [x] Wrist Flexion/Extension, 2-ch
  - [x] Wrist Pronation/Supination, 2-ch
  - [x] Flexion/Extension & Pronation/Supination, 4-ch

- [x] Arduino Angle-sEMG ADC
  - [x] sEMG read
  - [x] Angle read
