### ISSUE TITLE
Wrist Angle

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#40]
[Reports](https://github.com/dymnz/sEMG/tree/master/Reports/wang/semg_angle_est)

**Comment by dymnz** [comment]
### 1st Experiment

Wrist flexion/extension proportional control. sEMG to Wrist angle(*S2WA*).

Test if the two muscle is enough for wrist angle estimation.

* Muscle:
  * Extensor Digitorum
  * Flexor Digitorum Superficialis
* Pre-processing
  * Segmented w/ fixed window, others as before
* Possible pre-processing
  * ICA (Shouldn't be needed for 2-ch sEMG mounted on opposing side of the forearm)

**Comment by dymnz** [comment]
### 2nd Experiment

Flexion/Extension, better posture for cleaner signal.

* Muscle:
  * Extensor Digitorum
  * Flexor Digitorum Superficialis
* Protocol
  * Zero-load, palm facing down, making a fist
  * ~Wrist hang free w/ forearm resting on a surface~ Forearm and Wrist are on the table. For Flexion, knuckles are supposed to touch the table; for Extension, the bottom of the wrist is supposed to touch the table.
  * Constant angular speed
  * 0 degree is defined as palm facing down flat on the table, <0 degree as finger moving up
  * Each dataset consists of 5~10 epoch w/ resting interval in between each epoch
* Movement types
  * Extension: <0 degree only. From 0d move toward 90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_EXT_
  * Flexion: >0 degree only. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_FLX_
  * Extension/Flexion: Full range. From 0d move toward 90d then pause. Start moving toward 0d then pause. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_FULL_

**Comment by dymnz** [comment]
### 3rd Experiment

Flexion/Extension, better posture for cleaner signal, better muscle selection.

* Muscle:
  * Extensor Carpi Ulnaris 
  * Flexor Carpi Radialis
* Protocol
  * Zero-load, palm facing down, making a fist
  * ~Wrist hang free w/ forearm resting on a surface~ Forearm and Wrist are on the table. For Flexion, knuckles are supposed to touch the table; for Extension, the bottom of the wrist is supposed to touch the table.
  * Constant angular speed
  * 0 degree is defined as palm facing down flat on the table, <0 degree as finger moving up
  * Each dataset consists of 5~10 epoch w/ resting interval in between each epoch
  * R^2 error metric should be used to avoid bias for small value estimation
* Movement types
  * Extension: <0 degree only. From 0d move toward 90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_EXT_
  * Flexion: >0 degree only. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_FLX_
  * Extension/Flexion: Full range. From 0d move toward 90d then pause. Start moving toward 0d then pause. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_FULL_

**Comment by dymnz** [comment]
### 4th Experiment

Pronation/Supination. First test, try to locate optimal muscle location and check signal condition.

* Muscle:
  * Biceps Brachii (CH1)
  * ~Flexor Digitorum Superficialis~ Flexor Carpi Radialis (CH1)
* Protocol
  * Zero-load, palm facing down, making a fist
  * ~Wrist hang free w/ forearm resting on a surface~ Forearm and Wrist are on the table. Hand should always contact the table, to avoid raising forearm.
  * Constant angular speed
  * 0 degree is defined as palm facing down flat on the table, >0 as wrist turn right
  * Each dataset consists of 5~10 epoch w/ resting interval in between each epoch
  * R^2 error metric should be used to avoid bias for small value estimation
* Movement types
  * Pronation: <0 degree only. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_PRO_
  * Supination: >0 degree only. From 0d move toward 90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_SUP_
  * Extension/Flexion: Full range. From 0d move toward 90d then pause. Start moving toward 0d then pause. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_TABLE_2_FULL_

--- 

### 4th Experiment - Notes
* Can't locate *Supinator muscle*, no significant signal measured. Use *Biceps Brachii* instead.
* *Flexor Carpi Radialis* is right next to *Pronator Teres*
* *Biceps Brachii* has significant response for Supination, but raising the forearm also trigger *Biceps Brachii*. Have to avoid such movement when test.

**Comment by dymnz** [comment]
### 5th Experiment

Flexion/Extension using pot. Compare the angle calculated by pot. and IMU.

**Comment by dymnz** [comment]
### 6th Experiment

Flexion/Extension using pot. Compare the angle calculated by pot. and IMU.

**Comment by dymnz** [comment]
### 7th Experiment

Flexion/Extension using pot. Compare the angle calculated by pot. and IMU.

### TODO
- [ ] Finish Pot. device

**Comment by dymnz** [comment]
### 7th Experiment

Flexion/Extension using pot. Compare the angle calculated by pot. and IMU.

### TODO
- [ ] Finish Pot. device

**Comment by dymnz** [comment]
### 6-3 Experiment

Supination/Pronation part 3. Custom device to assist rotation. NO ICA

* Muscle:
  * Pronator Teres (CH1, red)
  * Supinator Muscle (CH2, green)  
* Protocol
  * Zero-load, palm facing down, making a fist
  * Forearm and Wrist are on the table. Hand should always contact the table, to avoid raising forearm.
  * Constant angular speed
  * ~0 degree is defined as palm facing down flat on the table~, 0 degree is defined as palm resting on table w/ thumb pointing up, >0 as wrist turn right (SUP).
  * **Resting position is palm down, all muscle relaxed, truning ~30d clockwise**
    * **The bias is removed in the preprocessing process, especially for Roll bias. (same in exp-5)**
  * **Ref. electrode moved to wrist**, follow the placement of other paper.
  * **Fixed custom device to assist PRO/SUP motion to avoid Flexion/Extension of wrist**
  * Each dataset consists of 5~10 epoch w/ resting interval in between each epoch
  * R^2 error metric should be used to avoid bias for small value estimation
* Movement types
  * Pronation: <0 degree only. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_6_PRO_ (S2WA_6_FREE_PRO_ for no device support)
  * Supination: >0 degree only. From 0d move toward 90d then pause. Start moving toward 0d then stop.
    * S2WA_6_SUP_ (S2WA_6_FREE_SUP_ for no device support)
  * Extension/Flexion: Full range. From 0d move toward 90d then pause. Start moving toward 0d then pause. From 0d move toward -90d then pause. Start moving toward 0d then stop.
    * S2WA_6_PROSUP_ (S2WA_6_FREE_PROSUP_ for no device support)

---

### 6th Experiment - LSTM, RMS @ 100pts, Downsampled @ 10hz - FULL-FULL - self

* ./rnn S2WA_6_SUP_1_DS10_RMS100_FULL S2WA_6_SUP_1_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0120586259
  * RMSE:  9.63882	 2.37195	
* ./rnn S2WA_6_SUP_1_DS10_RMS100_FULL S2WA_6_SUP_1_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0039227957
  * RMSE:  5.30285	 2.11082	
* ./rnn S2WA_6_SUP_1_DS10_RMS100_FULL S2WA_6_SUP_1_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0039981705
  * RMSE:  5.28122	 1.69413	
 
* ./rnn S2WA_6_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_2_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0039298734
  * RMSE:  5.38020	 1.78949	
* ./rnn S2WA_6_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_2_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0034587046
  * RMSE:  5.08325	 1.28027	
* ./rnn S2WA_6_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_2_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0020736674
  * RMSE:  3.45845	 2.32862	 

* ./rnn S2WA_6_SUP_3_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0042383119
  * RMSE:  5.67183	 1.79054	
* ./rnn S2WA_6_SUP_3_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0030042326
  * RMSE:  4.50368	 1.83670	
* ./rnn S2WA_6_SUP_3_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0019764212
  * RMSE:  3.72109	 1.01452	


* ./rnn S2WA_6_PRO_1_DS10_RMS100_FULL S2WA_6_PRO_1_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0031684317
  * RMSE:  4.16767	 2.82956	
* ./rnn S2WA_6_PRO_1_DS10_RMS100_FULL S2WA_6_PRO_1_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0024817709
  * RMSE:  3.56318	 2.74454	
* ./rnn S2WA_6_PRO_1_DS10_RMS100_FULL S2WA_6_PRO_1_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0019631552
  * RMSE:  3.59966	 1.65080	

* ./rnn S2WA_6_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_2_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0072794260
  * RMSE:  7.11921	 2.36746	
* ./rnn S2WA_6_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_2_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0033768638
  * RMSE:  4.81058	 1.25234	
* ./rnn S2WA_6_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_2_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0016810084
  * RMSE:  3.60954	 0.85308	

* ./rnn S2WA_6_PRO_3_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0059110437
  * RMSE:  6.11228	 3.42373	
* ./rnn S2WA_6_PRO_3_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0031684487
  * RMSE:  4.72995	 1.52940	
* ./rnn S2WA_6_PRO_3_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0021778309
  * RMSE:  3.93544	 1.40791	


---

### 6th Experiment - LSTM, ICA, RMS @ 100pts, Downsampled @ 10hz - FULL-FULL - cross

* ./rnn S2WA_6_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0043998457
  * RMSE:  6.00009	 2.02449	
* ./rnn S2WA_6_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0023466696
  * RMSE:  6.32396	 1.52043	
* ./rnn S2WA_6_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_SUP_3_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0014521266
  * RMSE:  8.44502	 1.25477	


* ./rnn S2WA_6_PRO_1_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0032574121
  * RMSE:  7.03811	 3.08717	
* ./rnn S2WA_6_PRO_1_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0054458753
  * RMSE:  6.50586	 1.91884	
* ./rnn S2WA_6_PRO_1_PRO_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0023258014
  * RMSE:  8.28340	 3.43738	

---

### 6th Experiment - LSTM, JOINT_ICA, RMS @ 100pts, Downsampled @ 10hz - FULL-FULL - cross


* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0162230805
  * RMSE: 13.03734	 3.10902	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0056536728
  * RMSE: 23.77072	 3.55651	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0044427993
  * RMSE:  7.57947	 3.83164	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 8000 10 100000 4
  * average loss at epoch:       7999 = 0.0204741149
  * RMSE:  9.03810	 3.29326	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 8 12000 10 100000 4
  * average loss at epoch:      11999 = 0.0100593159
  * RMSE: 10.98928	 3.23305	

* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 16 1000 10 100000 4
  * average loss at epoch:        999 = 0.0214140912
  * RMSE: 16.61689	 3.83099	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 16 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0140161749
  * RMSE: 15.73037	 3.69578	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PRO_3_DS10_RMS100_FULL 16 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0051393801
  * RMSE:  7.28086	 4.06423	


---

### 6th Experiment - LSTM, JOINT_ICA, RMS @ 100pts, Downsampled @ 10hz - FULL-FULL - PROSUP

From the validation above, epoch = 4000 should give the best result

* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0162230805
  * RMSE: 20.51659	 2.36710	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0056536728
  * RMSE: 21.29521	 2.38647	
* ./rnn S2WA_6_PRO_1_PRO_2_SUP_1_SUP_2_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0044427993
  * RMSE: 35.06863	 2.32083	
 

* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0177118158
  * RMSE: 25.46395	 2.86638	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0613867231
  * RMSE: 11.73656	 2.08380	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_1_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0097422229
  * RMSE: 19.19111	 2.48849	


* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0177118158
  * RMSE: 15.50791	 2.37371	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0613867231
  * RMSE: 10.71091	 1.85864	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0097422229
  * RMSE: 20.94776	 2.68542	

* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_PROSUP_1_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 1000 10 100000 4
  * average loss at epoch:        999 = 0.0136191681
  * RMSE: 11.37474	 1.71688	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_PROSUP_1_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 2000 10 100000 4
  * average loss at epoch:       1999 = 0.0080948319
  * RMSE: 11.11106	 1.77466	
* ./rnn S2WA_6_PRO_1_PRO_2_PRO_3_SUP_1_SUP_2_SUP_3_PROSUP_1_DS10_RMS100_FULL S2WA_6_PROSUP_2_DS10_RMS100_FULL 8 4000 10 100000 4
  * average loss at epoch:       3999 = 0.0055168896
  * RMSE: 10.11074	 1.72827	



* None of the testing can avoid *Torque and Gravity* issue, see below 

---

### 6th Experiment - Notes

* Pronator electrode location seems to be bad (**May be caused by Torque&Gravity issues**)
  * sEMG response:
    * Pronation: Pro(2) + Sup(1), in equal magnitude <-
    * Supination: Mostly Sup(1) 
* Small amplitude in both Pro&Sup, the force required to rotate forearm is too small
  * Torque may be needed, like in other paper
    * Heavier forearm?
    * Heavy load for hand?

* PRO/SUP performance are better, **What improves the test result?**
  1. Ref. electrode placement change
  2. Fixed device to assist motion
  3. Better muscle locating

---


### 6th Experiment - Issues

* *Torque and Gravity*
  * No torque is required when Gravity is assisting the movement (i.e. No muscle activity)
    * In the case of "0 degree is defined as palm resting on table w/ thumb pointing up", Gravity is helping the *Pronation* movement
    * See *Meeting 2018/04/20 - SEMG_WRIST_ANGLE_2* for more explanation
  * Possible solution
    * Switch back to "0 degree is defined as palm facing down flat on the table"
      * The reason to change in this experiment
        1. The neutral position for forearm should be "0 degree is defined as palm resting on table w/ thumb pointing up", where both SUP&PRO has ~90d displacement
        2. In "0 degree is defined as palm facing down flat on the table", SUP has a ~150d displacement, while PRO has ~60d
    * Custom device requires torque to turn
      * Requires a fixed torque for both clockwise & couter-clockwise rotation
        * How???

### TODO
- [ ] 6-2 Free hand results

**Comment by dymnz** [comment]
### 8th Experiment

Torque & Gravity Issue, see exp_6. Switch back to "0 degree is defined as palm facing down flat on the table", with device assisted PRO/SUP.

**Comment by dymnz** [comment]
### 10th Experiment

4-ch sEMG FLX/EXT(Pot.) & PRO/SUP(Gyro).

### TODO
- [ ] 4-ch sEMG hardware
  * Currently 2-ch
- [ ] Finish Pot. angle est.

**Comment by dymnz** [comment]
Currently working on exp 7-3.
PCA version of exp 7.
Compare the result of ICA and PCA and **Do nothing**.

old_ICA vs PCA under cross_valid
new_ICA debugging

### Does whitening for ICA/PCA makes sense?
### FastICA whitens the input signal, can ICA be applied on RMSed signal?

* ~w/o whitening~ FastICA whitens the signal, training data amp. norm., C-V patience:
  * ICA marginally better than PCA
  * H: 32>=24>=16 @ Patience > 40/100


Data: https://github.com/dymnz/sEMG/blob/master/Reports/wang/semg_angle_est/RMS_order.md
Organized: exp_6_ICA_compare.xlsx - exp_7 RMS order

**Comment by dymnz** [comment]
### PRO_SUP only training effectiveness

Do this for 4-ch sEMG

See [exp-10](https://github.com/dymnz/sEMG/blob/master/Reports/wang/semg_angle_est/exp_10.md): 
* Training sample can be reduced for "Full motion", though with slightly worse performance (~20%) see
  * Complex MIX, Reduced Simple/Mix Training
  * Complex MIX, Reduced Simple Training

**Comment by dymnz** [comment]
4-ch sEMG: https://github.com/dymnz/sEMG/issues/12#issuecomment-385875860

# Change Matlab code sampling rate to 460 SPS

* Working on Pot.
  * Need to find the angle -> voltage mapping
    * DOF: ? degree
    * Verifying linearity for 30~150 degree, w/ 90d as metal contact pointing down and handle parallel to the ground, angle decrease as handle approaches metal contact
      * 10d increment, see change in voltage
      * Voltage from 150d to 0d inc. 10d
        * 150d: 1170
        * 140d: 1410
        * 130d: 1690
        * 120d: 1960
        * 110d: 2250
        * 100d: 2530
        *   90d: 2805
        *   80d: 3070
        *   70d: 3350
        *   60d: 3610
        *   50d: 3865
        *   40d: 3950
        *   30d: 3962
      * Linear for 150 ~ 50d, 1170 ~ 3865, checking hand DOF see if angle stay in safe range
  * 1M ohm is too large, large noise. NOW USING 50k ohm
  * Zeroing is not perfect. Repeating the same movement but the voltage won't be the same afterwards
* TODO:
  - [x] Calculate equation for voltage-angle mapping, with different 0d point
  - [ ] Calculate zeroing error
  - [x] 0d positioning in Processing
    * Set the current measurement value as 0d on hand. Simply subtract the difference between current angle and 0d.

**Comment by dymnz** [comment]
PCA reconstruct?

**Comment by dymnz** [comment]
### Separate NN for PRO/SUP & FLX/EXT

**Comment by dymnz** [comment]
### TDSEP parameter test

For exp-10, see 'exp_10_prePro_compare'

**Comment by dymnz** [comment]
###

ICA, Impulse extraction,

### Wrist Movements
* DOF - 1 (Pitch):
  * Flexion: Palm facing down, moving **downward**
  * Extension: Palm facing down, moving **upward**
* DOF - 2 (Roll):
  * Pronation: Forearm turning **counter-clockwise**
    * ["pronation involves placing the palms into the prone (**face-down**) position, like someone would do when looking at the backs of their hands"](http://www.innerbody.com/image/musc03.html)
  * Supination: Forearm turning **clockwise**
    * ["The motion of supination turns the palms anteriorly or superiorly to the supine (**face-up**) position."](http://www.innerbody.com/image/musc03.html)
    * *In the anatomical position, with the arms extended to the sides of the trunk and palms facing forward, the arms are already in the supinated position.*
* DOF - 3 (Yaw):
  * Radial Deviation: Palm moving **counter-clockwise** on the **horizontal plane**
  * Ulnar Deviation: Palm moving **clockwise** on the **horizontal plane**

---

### Paper

* [A new strategy for multifunction myoelectric control(1993)](https://ieeexplore.ieee.org/document/204774/)
  * ANN chosen for fast training time

* [Surface EMG pattern recognition for real-time control of a wrist exoskeleton (2010)](https://www.ncbi.nlm.nih.gov/pubmed/20796304)

* [Simultaneous and Proportional Force Estimation for Multifunction Myoelectric Prostheses Using Mirrored Bilateral Training (2010)](https://ieeexplore.ieee.org/document/5551179/)
  * Wrist (2-DOF) FLX/EXT & RU-DEV
  * 7-ch sEMG
  * Multilayer Perceptron
  * Feature set performance: MSV(?) < TD = TD+6AR = TD+5 wavelet marginal(TDWV)(?)
  * 7-ch semg -> TD feature -> PCA -> MLP

* [Comparison of regression models for estimation of isometric wrist joint torques using surface electromyography (2011)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3198911/)


* [SVM for Estimation of Wrist Angle from Sonomyography And SEMG Signals (2011)](http://ieeexplore.ieee.org/document/4353415/)
  * Flexion/Extension

* [Wrist angle estimation based on musculoskeletal systems with EMG (2011)](http://ieeexplore.ieee.org/document/6072755/)
  * 4-ch, physical model
    * extensor carpi radialis longus
    * extensor carpi ulnaris
    * flexor carpi radialis
    * flexor carpi ulnaris

* [EMG-based simultaneous and proportional estimation of wrist/hand kinematics in uni-lateral trans-radial amputees (2012)](https://jneuroengrehab.biomedcentral.com/articles/10.1186/1743-0003-9-42)
  * Wrist (3-DOF), 7-ch sEMG, TDAR feature set, MLP
  * Intact-limbed: 
    * (3-DOF)72.8 +- 8.29% accuracy
    * ~DoF-12 90.6% ± 3.68% (CG group, motion 1/2/4/5, accounting PROSUP/FLXEXT)~ DOF2 is R/U deviation

* [Multichannel surface EMG based estimation of bilateral hand kinematics during movements at multiple degrees of freedom (2010)](https://ieeexplore.ieee.org/document/5627622/)
  * Previous work of above
  * Intact bodied, 5 grid w/ 16-ch each (80-ch)
  * Fullwave rectified sEMG
  * 3-DOF, w/ 6 separate MLP. MLP output filted w/ LPF 1Hz(?)
  * Coefficient of determination (variability explained by estimated values)
    * FLX/EXT: 82.7 +- 2.9%
    * PRO/SUP: 76.6 +- 11.8%

* [Simultaneous and proportional control of 2D wrist movements with myoelectric signals (2012)](http://ieeexplore.ieee.org/document/6349712/)
  * 192-ch sEMG array, nonlinear transformations, Flexion/Extension/RU-Deviation

* [Bayesian Filtering of Surface EMG for Accurate Simultaneous and Proportional Prosthetic Control (2014)](http://ieeexplore.ieee.org/document/7332757/)
  * 16-ch sEMG, Flexion/Extension or Pronation/Supination and simultaneously.
  * Feature extraction (amplitude summarizing) for NMF regressor, compare MAV and BAY summarizing performance

* [Quantifying Forearm Muscle Activity during Wrist and Finger Movements by Means of Multi-Channel Electromyography (2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4188712/)
  * 112-ch sEMG array

* [EMG-based learning approach for estimating wrist motion (2015)](https://www.researchgate.net/publication/283713267_EMG-based_learning_approach_for_estimating_wrist_motion)
  * Based on *EMG-based simultaneous and proportional estimation of wrist/hand kinematics in uni-lateral trans-radial amputees (2012)*
  * 11-ch sEMG, SVR
  * Wrist angle @ different arm position
  * Circular motion of FLX/EXT & RU-Deviation
  * Same day Same pose: 78% | Same day Across pose: 63% | Different day: 50 ~ 0%

* Continuous Estimation of Wrist Angles for Proportional Control Based on Surface Electromyography (2016)
  * 4-ch sEMG, BPNN w/ fixed windowed RMS pre-processing has the best result
  * Separate tests for Flexion/Extension/Pronation/Supination
  * RMSE | WF: 10.42 | WE: 8.23 | WS: 16.53 | WP: 13.09
  * Accuracy decrease in the presence of grip force

* [Continuous estimation of hand's joint angles from sEMG using wavelet-based features and SVR (2016)](https://dl.acm.org/citation.cfm?id=3051498)
  * SVR, DWT
  
* [EMG-Based Continuous and Simultaneous Estimation of Arm Kinematics in Able-Bodied Individuals and Stroke Survivors (2017)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5575159/)
  * NARX model (Recurrent NN), 3-DOF shoulder/Elbow/Wrist(FLX/EXT), 6-ch sEMG
  * LPF @ 4Hz, 99%+ accuracy

* [Continuous Motion Decoding from EMG Using Independent Component Analysis and Adaptive Model Training(2014)](https://www.ncbi.nlm.nih.gov/pubmed/25571132)
  * Mentioned Gaussian characteristic but used ICA???

#### May Be Relevant: 
* *[Neural network committees for finger joint angle estimation from surface EMG signals](https://biomedical-engineering-online.biomedcentral.com/articles/10.1186/1475-925X-8-2)*
* *[Real-time simultaneous and proportional myoelectric control using intramuscular EMG (2014)](http://iopscience.iop.org/article/10.1088/1741-2560/11/6/066013/pdf)*
* *[Estimation of finger joint angles from sEMG using a recurrent neural network with time-delayed input vectors (2009)](https://www.researchgate.net/publication/224580490_Estimation_of_finger_joint_angles_from_sEMG_using_a_recurrent_neural_network_with_time-delayed_input_vectors)*
* *[Extracting Simultaneous and Proportional Neural
Control Information for Multiple-DOF Prostheses
From the Surface Electromyographic Signal](https://ieeexplore.ieee.org/document/4663628/)
---

### Wrist movement muscle:
* Extension | *Should find which muscle other experiments are focusing on*
  * [Source](http://www.sportsinjuryclinic.net/anatomy/human-muscles/wrist-hand-joint-actions/wrist-extension) | **Highlighted** because used in [other paper](http://ieeexplore.ieee.org/document/6072755/)
    * Extensor Digitorum <- testing
    * **[Extensor Carpi Radialis Longus](https://en.wikipedia.org/wiki/Extensor_carpi_radialis_longus_muscle)**
    * **[Extensor Carpi Ulnaris](https://en.wikipedia.org/wiki/Extensor_carpi_ulnaris_muscle)** <-- Chosen
    * Extensor Pollicis Longus 
  * Characteristic
      * POWER: Linear transform of EMG
      * RMS: sqrt(POWER), non-linear
      * LOG-VAR: log(POWER), non-linear
  * Use non-linear transform to linearize relationship between Feature and Joint angle
    * Linear regression performance better w/ RMS, LOG-VAR
    * MLP is better w/ POWER
    * Linear regreesion w/ LOG-VAR has best performance

* Flexion | *Should find which muscle other experiments are focusing on*
  * [Source](http://www.sportsinjuryclinic.net/anatomy/human-muscles/wrist-hand-joint-actions/wrist-flexion) | **Highlighted** because used in [other paper](http://ieeexplore.ieee.org/document/6072755/)
    * **[Flexor Carpi Radialis](https://en.wikipedia.org/wiki/Flexor_carpi_radialis_muscle)** <-- Chosen
    * **[Flexor Carpi Ulnaris](https://en.wikipedia.org/wiki/Flexor_carpi_ulnaris_muscle)**
    * Flexor Digitorum Superficialis <- testing
    * Flexor Pollicis Longus (Thumb movement)

* Pronation | [Source](http://www.innerbody.com/image/musc03.html) | **Highlighted** = chosen
  * **[Pronator Teres](https://en.wikipedia.org/wiki/Pronator_teres_muscle)**: Near elbow
  * Pronator Quadratus: Near wrist (Hard to locate)
* Supination | [Source](http://www.innerbody.com/image/musc03.html) | **Highlighted** = chosen
  * **Supinator Muscle** : Near elbow (Hard to locate)
  * Biceps Brachii (Tried and failed)

**Comment by yenhuai77** [comment]
thx
