### ISSUE TITLE
Wrap Up

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#60]
- [x] 4 page
- [x] Zip and upload to Google drive
  - [x] CH/EN thesis (word & pdf)
  - [ ] Meeting prez. (pdf/ppt)
  - [x] Code
    * Including PCB layout
  - [x] Experiment procedure
    * Including data
- [ ] Proof of handover (YAO sig.)
